### PR TITLE
ADD Shiny app to visualize 2018 Regs stats

### PR DESCRIPTION
**Pull request by ryanrosenberg**
I created a Shiny app to visualize some graphs from 2018 Regs and figured it would fit well here.

### CODE REVIEW

**Comment by grapesmoker** [comment]
this seems cool

**Comment by hftf** [comment]
I appreciate that you're willing to share the source code for your Shiny app. However, I'm reluctant about this PR for a couple reasons:

* The two tsvs duplicate raw data that's already in the repo, and the all_cdf.csv seems to be derivable from the raw data.
* It doesn't quite fit what I had envisioned for this repository, which is simply a central resource to hold raw data only. I feel like analysis fits better in its own repo fully controlled by its author, because pushing updates wouldn’t require PRs/community review, and they can also be forked more easily. I'm also wary of monorepos that try to do too many things at once and end up with large parts that are irrelevant to most users, especially because git makes it difficult to clone only part of a repository. Anyway, these are the main options to consider:

  1. Redefine the purpose of the repository. (Discuss ideas below or in #1.) The license must be updated to cover source code.
  2. Keep the existing definition (and clarify it in the readme if necessary). Have separate repos for analysis, etc. (perhaps containing this repo as a submodule, so that the code can be coupled to a compatible version of the data); maybe add a document here that links to them. Scripts/other code are okay as long as they are generic and widely applicable (such as for doing routine data transformation), though require a license update.

To allow discussion, I won’t revert the merge right away, but I am leaning strongly toward option 2.

P.S. Not sure how I missed the notification for this – in the future, could we please wait more than 5 minutes before merging non-trivial PRs so that other people can be aware of them?

**Comment by grapesmoker** [comment]
I think option 2 is a good option. I'm not sure that code/data coupling ever works correctly, but you could try it. If you're going to have this repo as a data repository, I think it would be useful to outline what structure you think it should have.

**Comment by hftf** [comment]
I backed out the merge via a force push so that the repo size would not be needlessly inflated.

**Comment by ryanrosenberg** [comment]
Seems reasonable to me.

**Pull request merged**
